target("SkyrimScripting.Console")
    set_kind("static")
    add_files("src/*.cpp")
    add_includedirs("include", { public = true })
    add_headerfiles("include/(**.h)")
    add_deps("SkyrimScripting.Console.Shared", { public = true })
