target("SkyrimScripting.Console")
    set_kind("static")
    add_files("src/*.cpp")
    add_includedirs("include", { public = true })
    add_headerfiles("include/(**.h)")
    add_packages(get_config("commonlib"), { public = true })
    add_packages("global_macro_functions", { public = true })
    add_packages("function_pointer", { public = true })
    add_packages("collections", { public = true })
    add_packages("unordered_dense", { public = true })
    add_packages("SkyrimScripting.Services", { public = true })
